[project]
name = "deepgenerativemodels"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch (>=2.6.0,<3.0.0)",
    "lpips (>=0.1.4,<0.2.0)",
    "munch (>=4.0.0,<5.0.0)",
    "matplotlib (>=3.10.0,<4.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "gdown (>=5.2.0,<6.0.0)",
    "tensorboard (>=2.19.0,<3.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
yadisk = "^3.2.0"
jupyter = "^1.1.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
